version: '2.3'
services:
  postgres:
    hostname: postgres
    image: postgres:9.5
    environment:
    - POSTGRES_USER=user
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=postgres
    ports:
    - 5433:5432
    volumes:
    - ./data/pgdata/master:/var/lib/postgresql/data
    - ./conf/pginit:/docker-entrypoint-initdb.d